name: .NET Framework WinForms Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore Pharmacy-management.sln

    - name: Build solution
      run: msbuild YourSolution.sln /p:Configuration=Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Pharmacy Management App
        path: Pharmacy-management\bin\Release\